[package]
name = "emote-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
ravif = "0.11.11"
rayon = "1.10.0"
webp-animation = "0.9.0"

[profile.release]
opt-level = 3        # Уменьшение уровня оптимизации (по умолчанию: 3)
